keybinding:
    universal:
        prevItem: e
        nextItem: n
        prevItem-alt: e
        nextItem-alt: n
        prevBlock: h
        nextBlock: i
        prevBlock-alt: h
        nextBlock-alt: i
        scrollUpMain-alt1: E
        scrollDownMain-alt1: N
        nextTab: ']'
        prevTab: '['
        nextMatch: k
        prevMatch: K
    files:
        ignoreFile: l
    branches:
        viewGitFlowOptions: l
    commits:
        moveDownCommit: <c-n>
        moveUpCommit: <c-e>
        startInteractiveRebase: l
    submodules:
        init: l